### ISSUE TITLE
Unsupported distro: endeavouros

### ISSUE THREAD

**Issue by Landixbtw** [alexjercan/nvim.dotfiles#1]
Hey, I was going to install your config since I really like it. But apparently endeavourOS is not supported. Would love for you to add it to the supported distros.

**Comment by alexjercan** [comment]
Hi! I think it was just a matter of adding the name of the distro in the install script. Can you check if the `feature/endeavouros` branch works?

```
git fetch origin
git checkout feature/endeavouros
./install
```

**Comment by Landixbtw** [comment]
This works, I guess. But there are a few things that dont work. I believe. 

The bar down here is missing. 

![grafik](https://github.com/alexjercan/nvim.dotfiles/assets/68870626/f56dbdae-ec8e-4252-ab06-f6986f1ca6dc)

And what is the default leader key ? To access the whichkey

**Comment by alexjercan** [comment]
The default leader key in neovim is spacebar, you can change it in https://github.com/alexjercan/nvim.dotfiles/blob/master/nvim/lua/neovim/remap.lua#L1C1-L1C22 For tmux it is `ctrl+space`. 

The bar is missing because you need to start tmux. You can check out this script https://github.com/alexjercan/nvim.dotfiles/blob/master/scripts/tmux-sessionizer which should be available in `~/.local/bin`. I would change `selected=$(find ~/personal ~/work -mindepth 1 -maxdepth 1 -type d | fzf)` in here `~/personal` and `~/work` with the directory where you keep your projects. I don't have a good way of doing it right now so it is a bit manual :).
